"""Add user_id coulum to Log model

Revision ID: 7979534ffd6c
Revises: b74e442025a0
Create Date: 2024-04-20 19:53:02.517258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7979534ffd6c'
down_revision: Union[str, None] = 'b74e442025a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'user_id')
    # ### end Alembic commands ###
