"""Add url coulum to Log model

Revision ID: b74e442025a0
Revises: 23e77fadd6ea
Create Date: 2024-04-20 19:43:13.732371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e442025a0'
down_revision: Union[str, None] = '23e77fadd6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'url')
    # ### end Alembic commands ###
